services:
  golang-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - golang-postgres
    depends_on:
      - db

  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: go
      POSTGRES_PASSWORD: go
      POSTGRES_DB: go
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - golang-postgres

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - golang-postgres

volumes:
  postgres_data:

networks:
  golang-postgres:
    driver: bridge


